### ISSUE TITLE
VGG16 size is 224,224

### ISSUE THREAD

**Issue by minhdl93** [irfanICMLL/Auto_painter#2]
Hi,

I try to implement your code. 

I downloaded VGG16 model from https://github.com/machrisaa/tensorflow-vgg and put it in my_vgg folder. However, when I run the program, it shows the log like this. Could you help me with this error? Thank you.

> /usr/bin/python2.7 /data2/texttophoto/Auto_painter/training&test/auto-painter.py --mode train --input_dir /data2/texttophoto/Auto_painter/preprocessing/gen_sketch/pic_sketch/ --output_dir /data2/texttophoto/Auto_painter/preprocessing/gen_sketch/pic_color/ --checkpoint None
aspect_ratio = 1.0
batch_size = 1
beta1 = 0.5
checkpoint = None
display_freq = 0
f_weight = 0.0001
flip = True
gan_weight = 1
input_dir = /data2/texttophoto/Auto_painter/preprocessing/gen_sketch/pic_sketch/
l1_weight = 50.0
lr = 2e-05
max_epochs = 20
max_steps = None
mode = train
ndf = 48
ngf = 48
output_dir = /data2/texttophoto/Auto_painter/preprocessing/gen_sketch/pic_color/
output_filetype = png
progress_freq = 50
save_freq = 5000
scale_size = 530
seed = 1242561248
summary_freq = 100
trace_freq = 0
tv_weight = 0.001
examples count = 819
/data2/texttophoto/Auto_painter/training&test/my_vgg/vgg16.npy
npy file loaded
/data2/texttophoto/Auto_painter/training&test/my_vgg/vgg16.npy
npy file loaded
Traceback (most recent call last):
  File "/data2/texttophoto/Auto_painter/training&test/auto-painter.py", line 714, in <module>
    main()
  File "/data2/texttophoto/Auto_painter/training&test/auto-painter.py", line 549, in main
    model = create_model(examples.inputs, examples.targets, net1, net2)
  File "/data2/texttophoto/Auto_painter/training&test/auto-painter.py", line 373, in create_model
    gen_loss_f = tf.reduce_mean(tf.abs(feature_loss(targets,net1) - feature_loss(outputs,net2)))
  File "/data2/texttophoto/Auto_painter/training&test/auto-painter.py", line 335, in feature_loss
    vgg.build(image)
  File "/data2/texttophoto/Auto_painter/training&test/my_vgg/vgg16.py", line 36, in build
    assert red.get_shape().as_list()[1:] == [224, 224, 1]
AssertionError
build model started
Process finished with exit code 1

**Comment by xjrelc** [comment]
my solution is add this before line335:
image = tf.image.resize_images(image, [224, 224], method=tf.image.ResizeMethod.BICUBIC)
it's show like that:
def feature_loss(image , vgg):
        image = tf.image.resize_images(image, [224, 224], method=tf.image.ResizeMethod.BICUBIC)
        vgg.build(image)
        loss = vgg.conv3_2
        return loss
hope this can help you^-^

**Comment by giddyyupp** [comment]
another solution if you do not want to resize your images to 224x224 is that:
- in the vgg16.py file, comment these lines: 36, 37, 38, 44, and 69-78 (including both ends!)
since the loss only needs up to conv3_2 layer, you can feed any sized image to vgg if you comment all fc layers.

**Comment by minhdl93** [comment]
The problem was answered, issue closed.
